# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'get_latest_by': 'buy_date', 'verbose_name': 'Purchased lesson'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='when_waste_money_notification_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
